# Generated by Django 3.1.7 on 2021-03-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='Author',
            field=models.CharField(default='author', max_length=50),
        ),
    ]
